version: 2
jobs:
  build:
    working_directory: ~/bertha-client

    docker:
      - image: callum85/node-with-flow:0.0.1

    steps:
      - checkout

      # preparation
      - restore_cache:
          key: bertha-client-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: bertha-client-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run: yarn cache dir

      # code verifiers
      - run:
          name: ESLint
          command: ./node_modules/.bin/eslint .
      - run:
          name: Flow type-checking
          command: flow

      # compile
      - run:
          name: Compile with babel
          command: yarn run build

      # test
      - run:
          name: AVA tests
          command: ./node_modules/.bin/ava

      # finishing up
      - store_artifacts:
          path: dist/

      # TODO deploy
